apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: ollama-openwebui
  annotations:
    scenarios.ai.sap.com/description: "Run a ollama with Open Web UI server on SAP AI Core"
    scenarios.ai.sap.com/name: "ollama-openwebui"
    executables.ai.sap.com/description: "ollama-openwebui service"
    executables.ai.sap.com/name: "ollama-openwebui"
  labels:
    scenarios.ai.sap.com/id: "ollama-openwebui"
    ai.sap.com/version: "0.0.1"
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: infer.s
    spec: |
      predictor:
        minReplicas: 1
        maxReplicas: 1
        containers:
        - name: kserve-container
          image: docker.io/open-webui/open-webui:ollama
          ports:
            - containerPort: 8080
              protocol: TCP
